/** @type {import("../verity_knowledge_data.js").KnowledgeEntry[]} */
export const MORE_MC_KNOWLEDGE = [
	{ patterns: [/\bhow to craft a bed\b/], keywords: ["craft", "bed", "sleep", "wool"], answers: ["Tres lanas en la fila de arriba y tres tablas abajo en la mesa de crafteo. El color depende de la lana."] },
	{ patterns: [/\bhow to craft torches\b/], keywords: ["torch", "craft", "coal", "stick"], answers: ["Carbón o carbón vegetal sobre un palo: da 4 antorchas. Nivel de luz 14."] },
	{ patterns: [/\bhow to craft a pickaxe\b/], keywords: ["pickaxe", "craft", "mine", "tool"], answers: ["Tres del material en la fila de arriba y dos palos verticales al centro: madera, piedra, hierro, diamante, netherita."] },
	{ patterns: [/\bhow to craft a sword\b/], keywords: ["sword", "craft", "weapon", "fight"], answers: ["Material arriba al centro, otro debajo y un palo abajo al centro. Filo ayuda más adelante."] },
	{ patterns: [/\bhow to craft an axe\b/], keywords: ["axe", "craft", "chop", "wood"], answers: ["Dos del material en diagonal arriba a la izquierda y palo debajo: corta madera más rápido y es un arma decente."] },
	{ patterns: [/\bhow to craft a shovel\b/], keywords: ["shovel", "craft", "dig", "dirt"], answers: ["Uno del material arriba al centro y dos palos debajo: la tierra, arena y grava vuelan."] },
	{ patterns: [/\bhow to craft a hoe\b/], keywords: ["hoe", "craft", "farm", "till"], answers: ["Dos del material en la fila de arriba y palos al centro debajo: ara la tierra para los cultivos."] },
	{ patterns: [/\bhow to craft a bucket\b/], keywords: ["bucket", "craft", "water", "lava"], answers: ["Lingotes de hierro en forma de V: carga agua, lava, leche, ajolotes y peces."] },
	{ patterns: [/\bhow to craft a furnace\b/], keywords: ["furnace", "craft", "smelt", "cobble"], answers: ["Ocho piedras en anillo cuadrado: funde mineral, cocina comida y hace carbón vegetal."] },
	{ patterns: [/\bhow to craft a crafting table\b/], keywords: ["crafting", "table", "bench", "planks"], answers: ["Cuatro tablas en un cuadrado de 2x2 en tu inventario: desbloquea las recetas de 3x3."] },
	{ patterns: [/\bhow to craft chest\b/], keywords: ["chest", "craft", "storage", "wood"], answers: ["Ocho tablas en anillo cuadrado: 27 espacios. Dos juntos hacen un cofre doble."] },
	{ patterns: [/\bhow to craft boat\b/], keywords: ["boat", "craft", "water", "travel"], answers: ["Cinco tablas en forma de U: el viaje oceánico más rápido del inicio. El bote con cofre guarda objetos."] },
	{ patterns: [/\bhow to craft bow\b/], keywords: ["bow", "craft", "arrow", "shoot"], answers: ["Tres palos y tres cuerdas en patrón: necesita flechas. El encantamiento Infinidad es un lujo."] },
	{ patterns: [/\bhow to craft arrows\b/], keywords: ["arrow", "craft", "flint", "feather"], answers: ["Pedernal arriba, palo en medio, pluma abajo: uno de cada hace 4 flechas."] },
	{ patterns: [/\bhow to craft shield\b/], keywords: ["shield", "craft", "block", "iron"], answers: ["Tablas llenando la cuadrícula excepto un lingote de hierro arriba al centro: bloquea daño frontal."] },
	{ patterns: [/\bhow to make iron\b/, /\bhow to smelt iron\b/], keywords: ["iron", "smelt", "ore", "ingot"], answers: ["Funde hierro crudo o mineral de hierro en el horno: el mineral requiere pico de piedra o mejor."] },
	{ patterns: [/\bhow to get food\b/, /\bwhat food\b/], keywords: ["food", "eat", "hunger", "farm"], answers: ["Caza animales, cultiva trigo para pan, pesca y cocina la carne para mejor saturación. Las zanahorias doradas son endgame."] },
	{ patterns: [/\bhow to breed animals\b/], keywords: ["breed", "animal", "farm", "wheat"], answers: ["Dales su comida de cría: trigo a vacas, semillas a gallinas, zanahorias a cerdos, bayas a zorros. Corazones significan bebé en camino."] },
	{ patterns: [/\bhow to tame a wolf\b/], keywords: ["tame", "wolf", "dog", "bone"], answers: ["Dale huesos hasta que salgan corazones: collar, te sigue y ataca lo que tú golpees."] },
	{ patterns: [/\bhow to tame a cat\b/], keywords: ["tame", "cat", "ocelot", "fish"], answers: ["Dale bacalao o salmón crudo a los gatos callejeros: espantan creepers cuando están cerca."] },
	{ patterns: [/\bhow to find village\b/], keywords: ["find", "village", "villager", "trade"], answers: ["Explora llanuras, desierto, sabana, taiga. Pídeme localizar una: puedo escanear."] },
	{ patterns: [/\bhow to trade\b/, /\bhow do villagers trade\b/], keywords: ["trade", "villager", "emerald", "job"], answers: ["Interactúa con un aldeano que tenga su puesto de trabajo cerca: esmeraldas por bienes. Curarlo de zombi da descuentos."] },
	{ patterns: [/\bwhat is a librarian\b/], keywords: ["librarian", "villager", "book", "enchant"], answers: ["El bibliotecario comercia libros encantados: su puesto es el atril. Reinicia sus ofertas rompiendo el bloque con cuidado."] },
	{ patterns: [/\bwhat is a farmer\b/], keywords: ["farmer", "villager", "crop", "food"], answers: ["El granjero comercia cultivos y zanahorias doradas: su puesto es la compostadora. Bueno para la economía de comida."] },
	{ patterns: [/\bwhat is obsidian\b/], keywords: ["obsidian", "portal", "lava", "water"], answers: ["La obsidiana se forma cuando el agua toca lava de fuente: pico de diamante o mejor para minarla. El marco del portal necesita 10 o más."] },
	{ patterns: [/\bwhat is cobblestone\b/], keywords: ["cobble", "cobblestone", "stone", "mine"], answers: ["Minar piedra con pico da roca: material básico de construcción y para el horno."] },
	{ patterns: [/\bwhat is gravel\b/], keywords: ["gravel", "flint", "fall", "block"], answers: ["La grava cae como la arena: mínala por pedernal para flechas. Está bajo tierra y en playas."] },
	{ patterns: [/\bwhat is sand\b/], keywords: ["sand", "glass", "desert", "fall"], answers: ["La arena cae y se funde en vidrio: desiertos y playas. La arena roja está en las badlands."] },
	{ patterns: [/\bwhat is clay\b/], keywords: ["clay", "brick", "terracotta", "ball"], answers: ["Las bolas de arcilla salen de minar bloques de arcilla: fúndelas en ladrillos o tiñe terracota. Ríos y cuevas frondosas."] },
	{ patterns: [/\bwhat is wool\b/], keywords: ["wool", "sheep", "bed", "color"], answers: ["Esquila ovejas o combina cuerdas: las camas necesitan lana, hay 16 colores de tinte."] },
	{ patterns: [/\bwhat is leather\b/], keywords: ["leather", "cow", "armor", "book"], answers: ["Las vacas y caballos sueltan cuero: armadura, marcos de objetos y libros con papel."] },
	{ patterns: [/\bwhat is paper\b/], keywords: ["paper", "sugar", "cane", "book"], answers: ["Tres cañas de azúcar en fila: libros, mapas, cohetes. Cultiva la caña junto al agua."] },
	{ patterns: [/\bwhat is sugar cane\b/], keywords: ["sugar", "cane", "reed", "farm"], answers: ["Crece en arena o tierra junto al agua, hasta 3 bloques. Fuente de papel y azúcar."] },
	{ patterns: [/\bwhat is bamboo\b/], keywords: ["bamboo", "jungle", "panda", "scaffold"], answers: ["Planta de jungla de crecimiento rápido: los pandas lo comen, sirve para andamios y palos en masa."] },
	{ patterns: [/\bwhat is kelp\b/], keywords: ["kelp", "ocean", "fuel", "dried"], answers: ["Planta submarina: los bloques de alga seca sirven de combustible, y el alga seca es un bocadillo rápido."] },
	{ patterns: [/\bwhat is a saddle\b/], keywords: ["saddle", "horse", "pig", "ride"], answers: ["No se puede craftear en vanilla: mazmorras, pesca o comercio con aldeanos. Sirve para montar caballos, cerdos y striders."] },
	{ patterns: [/\bwhat is an anvil\b/], keywords: ["anvil", "repair", "enchant", "rename"], answers: ["Tres bloques de hierro arriba, cuatro lingotes abajo más el centro: repara equipo, combina encantamientos y renombra."] },
	{ patterns: [/\bwhat is lapis\b/], keywords: ["lapis", "enchant", "blue", "ore"], answers: ["El lapislázuli sale de su mineral: obligatorio para la mesa de encantamientos. Mina cerca de Y 0 desde la 1.18."] },
	{ patterns: [/\bwhat is emerald\b/], keywords: ["emerald", "village", "trade", "ore"], answers: ["La moneda de los aldeanos: también es un mineral raro de montaña. Comerciar suele ganarle a minarlas."] },
	{ patterns: [/\bwhat is coal\b/], keywords: ["coal", "fuel", "torches", "ore"], answers: ["Combustible común y material de antorchas: arde en el horno, y con palos hace antorchas."] },
	{ patterns: [/\bwhat is charcoal\b/], keywords: ["charcoal", "fuel", "smelt", "wood"], answers: ["Funde troncos en el horno: mismo valor de combustible que el carbón, renovable de los árboles."] },
	{ patterns: [/\bwhat is a spawn\b/], keywords: ["spawn", "respawn", "bed", "point"], answers: ["Donde apareces: el spawn del mundo al inicio, la cama fija tu reaparición personal. La brújula apunta al spawn del mundo."] },
	{ patterns: [/\bwhat is coordinates\b/, /\bwhat are coordinates\b/], keywords: ["coord", "xyz", "f3", "position"], answers: ["X es este-oeste, Y la altura, Z norte-sur: F3 o los ajustes las muestran. Yo leo las tuyas cuando me preguntas."] },
	{ patterns: [/\bwhat is fall damage\b/], keywords: ["fall", "damage", "height", "land"], answers: ["Caer duele después de 3 bloques: agua, heno, slime o caída lenta lo anulan. El clásico MLG con cubo de agua."] },
	{ patterns: [/\bwhat is hunger effect\b/], keywords: ["hunger", "effect", "husk", "food"], answers: ["El efecto Hambre vacía la barra de comida más rápido: lo causan los husks. Come más mientras esté activo."] },
	{ patterns: [/\bwhat is poison\b/], keywords: ["poison", "effect", "cave", "spider"], answers: ["El veneno daña con el tiempo pero no mata: te deja en medio corazón. La leche lo cura. Lo infligen las arañas de cueva."] },
	{ patterns: [/\bwhat is wither effect\b/], keywords: ["wither", "effect", "black", "hearts"], answers: ["El decaimiento vuelve negros los corazones y drena la vida: lo causan los esqueletos de wither y el jefe Wither. Las manzanas doradas ayudan."] },
	{ patterns: [/\bhow to fly\b/, /\bcan i fly\b/], keywords: ["fly", "creative", "elytra", "spectator"], answers: ["En supervivencia: élitros más cohetes, o caída lenta. En creativo y espectador vuelas gratis."] },
	{ patterns: [/\bhow to swim\b/], keywords: ["swim", "water", "drown", "bubble"], answers: ["Doble toque adelante bajo el agua o mantén el sprint: las burbujas se acaban sin el encantamiento Respiración o el truco de las puertas."] },
];
