// verity_espanol.js — Capa de entrada en español para Verity.
// Traduce mensajes en español a palabras clave en inglés ANTES de que
// el resto del addon los procese, así todos los patrones originales
// (regex e intenciones en inglés) funcionan también en español.
// Los mensajes en inglés pasan sin cambios (modo bilingüe).

const MAPA_ACENTOS = {
	"á": "a", "é": "e", "í": "i", "ó": "o", "ú": "u", "ü": "u", "ñ": "n",
	"Á": "a", "É": "e", "Í": "i", "Ó": "o", "Ú": "u", "Ü": "u", "Ñ": "n",
};

/** @param {string} s */
function quitarAcentos(s) {
	return s.replace(/[áéíóúüñÁÉÍÓÚÜÑ]/g, (c) => MAPA_ACENTOS[c] ?? c);
}

// Palabras que delatan que el mensaje está en español.
const PISTAS_ES =
	/\b(que|donde|dónde|como|cómo|cual|cuál|quien|quién|cuando|cuándo|cuanto|cuánto|cuantos|hola|buenas|buenos|gracias|adios|por favor|porfa|ayuda|ayudame|dime|dame|busca|buscar|encuentra|encontrar|localiza|quiero|puedes|puedo|necesito|estoy|eres|soy|tengo|tienes|hay|aqui|aquí|cerca|lejos|aldea|pueblo|bioma|mina|minar|diamante|diamantes|hierro|oro|coordenadas|hora|noche|dia|día|sigueme|sígueme|ven|quedate|quédate|canta|cancion|canción|musica|música|toca|cuentame|cuéntame|chiste|jugar|casa|comida|dormir|perdido|morir|mori|morí|te amo|te quiero|callate|cállate|tonto|tonta|estupido|estúpido|idiota|si|sí|nada|algo|mucho|muy|tambien|también|el|la|los|las|un|una|es|esta|está|para|pero|con|sin|del|de la)\b/i;

// Frases completas primero (se aplican antes que palabras sueltas).
// Todo en minúsculas y SIN acentos (el texto ya viene normalizado).
const FRASES = [
	// --- sociales / identidad ---
	["quien te creo", "who made you"],
	["quien te hizo", "who made you"],
	["quien te programo", "who made you"],
	["quien es tu creador", "who is your creator"],
	["quien es thatmob", "who is thatmob"],
	["quien es pntmc", "who is pntmc"],
	["como te llamas", "what is your name"],
	["cual es tu nombre", "what is your name"],
	["quien eres tu", "who are you"],
	["quien eres", "who are you"],
	["que eres tu", "what are you"],
	["que eres", "what are you"],
	["cuantos anos tienes", "how old are you"],
	["que edad tienes", "how old are you"],
	["como estas hoy", "how are you today"],
	["como estas", "how are you"],
	["como te va", "how is it going"],
	["como va todo", "how is it going"],
	["que tal", "how are you"],
	["que haces", "what are you doing"],
	["que puedes hacer", "what can you do"],
	["que sabes hacer", "what can you do"],
	["en que me puedes ayudar", "what can you help me with"],
	["buenos dias", "good morning"],
	["buenas tardes", "good afternoon"],
	["buenas noches", "good night"],
	["buenas", "hello"],
	["hasta luego", "see you later"],
	["nos vemos", "see you"],
	["mucho gusto", "nice to meet you"],
	["encantado de conocerte", "nice to meet you"],
	["te quiero", "i love you"],
	["te amo", "i love you"],
	["eres mi amigo", "are you my friend"],
	["eres mi amiga", "are you my friend"],
	["somos amigos", "are we friends"],
	["te extrane", "i missed you"],
	["te extrano", "i miss you"],
	["cuentame un chiste", "tell me a joke"],
	["dime un chiste", "tell me a joke"],
	["hazme reir", "make me laugh"],
	["cuentame una historia", "tell me a story"],
	["estoy triste", "i am sad"],
	["estoy feliz", "i am happy"],
	["estoy aburrido", "i am bored"],
	["estoy aburrida", "i am bored"],
	["estoy asustado", "i am scared"],
	["estoy asustada", "i am scared"],
	["tengo miedo", "i am scared"],
	["estoy estresado", "i am stressed"],
	["estoy estresada", "i am stressed"],
	["estoy enojado", "i am angry"],
	["estoy enojada", "i am angry"],
	["estoy molesto", "i am angry"],
	["estoy solo", "i am lonely"],
	["estoy sola", "i am lonely"],
	["me siento solo", "i feel lonely"],
	["me siento sola", "i feel lonely"],
	["estoy emocionado", "i am excited"],
	["estoy emocionada", "i am excited"],
	["estoy orgulloso", "i am proud"],
	["estoy cansado", "i am tired"],
	["estoy cansada", "i am tired"],
	["tengo sueno", "i am tired"],
	["lo logre", "i did it"],
	["lo consegui", "i did it"],
	["estas bien", "are you okay"],
	["estas ahi", "are you there"],
	["sigues ahi", "are you still there"],
	["me escuchas", "can you hear me"],
	["me oyes", "can you hear me"],
	["te odio", "i hate you"],
	["callate", "shut up"],
	["eres inutil", "you are useless"],
	["eres basura", "you are trash"],
	["eres tonto", "you are stupid"],
	["eres tonta", "you are stupid"],
	["eres estupido", "you are stupid"],
	["eres estupida", "you are stupid"],
	["eres feo", "you are ugly"],
	["eres fea", "you are ugly"],
	["lo siento", "i am sorry"],
	["perdon", "sorry"],
	["perdoname", "forgive me"],
	["de nada", "you are welcome"],
	["muchas gracias", "thank you very much"],
	["esta bien", "okay"],
	["no importa", "never mind"],
	["no se", "i dont know"],
	["no lo se", "i dont know"],
	["dejame pensar", "let me think"],
	["en serio", "really"],
	["es en serio", "are you serious"],
	["hablas en serio", "are you serious"],
	["por que", "why"],
	["hablemos", "lets talk"],
	["quieres hablar", "do you want to talk"],
	["hablas espanol", "do you speak spanish"],
	// --- mundo / navegacion ---
	["donde estoy", "where am i"],
	["en donde estoy", "where am i"],
	["donde estamos", "where are we"],
	["estoy perdido", "i am lost"],
	["estoy perdida", "i am lost"],
	["me perdi", "i am lost"],
	["cuales son mis coordenadas", "what are my coordinates"],
	["mis coordenadas", "my coordinates"],
	["que hora es", "what time is it"],
	["cual es la hora", "what time is it"],
	["es de noche", "is it night"],
	["es de dia", "is it day"],
	["como esta el clima", "what is the weather"],
	["que clima hace", "what is the weather"],
	["como esta el tiempo", "what is the weather"],
	["va a llover", "is it going to rain"],
	["haz que llueva", "make it rain"],
	["quiero que llueva", "make it rain"],
	["en que dimension estoy", "what dimension am i in"],
	["que dimension es esta", "what dimension is this"],
	["en que bioma estoy", "what biome am i in"],
	["que bioma es este", "what biome is this"],
	["que bioma es", "what biome is this"],
	["donde esta el spawn", "where is spawn"],
	["hacia donde miro", "which way am i facing"],
	["hacia donde estoy mirando", "which way am i facing"],
	["en que direccion estoy mirando", "which way am i facing"],
	["que tan lejos esta", "how far is it"],
	["que tan lejos", "how far"],
	["a que distancia", "how far"],
	["esta lejos", "is it far"],
	["esta cerca", "is it close"],
	["cuantos jugadores hay", "how many players are here"],
	["quien esta jugando", "who is playing"],
	["estoy a salvo", "am i safe"],
	["es seguro aqui", "is it safe here"],
	["cuanta vida tengo", "how much health do i have"],
	["cuanta hambre tengo", "how hungry am i"],
	["que es eso", "what is that"],
	["que animal es ese", "what mob is that"],
	["que mob es ese", "what mob is that"],
	// --- localizar estructuras ---
	["donde hay una aldea", "where is a village"],
	["donde hay un pueblo", "where is a village"],
	["donde puedo comerciar", "where would people trade"],
	["donde viven los aldeanos", "where do villagers live"],
	["llevame a una aldea", "take me to a village"],
	["fortaleza del end", "stronghold"],
	["fortaleza del nether", "nether fortress"],
	["templo del desierto", "desert temple"],
	["piramide del desierto", "desert pyramid"],
	["templo de la jungla", "jungle temple"],
	["templo de la selva", "jungle temple"],
	["mansion del bosque", "woodland mansion"],
	["monumento oceanico", "ocean monument"],
	["monumento del oceano", "ocean monument"],
	["barco hundido", "shipwreck"],
	["mina abandonada", "mineshaft"],
	["ciudad antigua", "ancient city"],
	["ciudad del end", "end city"],
	["portal en ruinas", "ruined portal"],
	["portal roto", "ruined portal"],
	["tesoro enterrado", "buried treasure"],
	["puesto de saqueadores", "pillager outpost"],
	["ruinas oceanicas", "ocean ruins"],
	["cabana de bruja", "witch hut"],
	["cabana de la bruja", "witch hut"],
	["camaras de prueba", "trial chambers"],
	["camara de pruebas", "trial chambers"],
	["ruinas de senderos", "trail ruins"],
	["restos de bastion", "bastion remnant"],
	// --- ordenes ---
	["ven aqui", "come here"],
	["ven aca", "come here"],
	["ven conmigo", "come with me"],
	["sigueme", "follow me"],
	["deja de seguirme", "stop following me"],
	["ya no me sigas", "stop following me"],
	["no me sigas", "stop following me"],
	["quedate aqui", "stay here"],
	["quedate quieto", "stay here"],
	["quedate quieta", "stay here"],
	["esperame aqui", "wait here"],
	["espera aqui", "wait here"],
	["toca musica", "play music"],
	["pon musica", "play music"],
	["reproduce musica", "play music"],
	["toca una cancion", "play a song"],
	["canta una cancion", "sing a song"],
	["cantame algo", "sing me something"],
	["para la musica", "stop the music"],
	["detén la musica", "stop the music"],
	["deten la musica", "stop the music"],
	["apaga la musica", "stop the music"],
	["haz el sonido de", "make the sound of a"],
	["haz un sonido de", "make the sound of a"],
	["cual es el sonido de", "what is the sound of a"],
	["como suena", "what sound does it make"],
	["mas fuerte", "louder"],
	["mas bajo", "quieter"],
	["otra vez", "again"],
	["de nuevo", "again"],
	// --- consejos / juego ---
	["como consigo comida", "how do i get food"],
	["tengo hambre", "i am hungry"],
	["como hago una casa", "how do i build a shelter"],
	["como construyo una casa", "how do i build a shelter"],
	["necesito un refugio", "i need a shelter"],
	["como sobrevivo la noche", "how do i survive the night"],
	["como empiezo", "how do i start"],
	["que hago primero", "what should i do first"],
	["que hago ahora", "what should i do now"],
	["que deberia hacer", "what should i do"],
	["estoy atrapado", "i am stuck"],
	["estoy atrapada", "i am stuck"],
	["me quede atrapado", "i am stuck"],
	["estoy en un hoyo", "i am stuck in a hole"],
	["como salgo de aqui", "how do i get out"],
	["me estoy muriendo", "i am dying"],
	["acabo de morir", "i just died"],
	["perdi mis cosas", "i lost my stuff"],
	["perdi todo", "i lost everything"],
	["como llego al nether", "how do i get to the nether"],
	["como voy al nether", "how do i get to the nether"],
	["como llego al end", "how do i get to the end"],
	["como mato al dragon", "how do i kill the dragon"],
	["como derroto al dragon", "how do i beat the dragon"],
	["donde encuentro diamantes", "where do i find diamonds"],
	["donde hay diamantes", "where are diamonds"],
	["en que capa estan los diamantes", "what level are diamonds"],
	["como consigo netherita", "how do i get netherite"],
	["restos antiguos", "ancient debris"],
	["como domestico", "how do i tame a"],
	["como hago una granja", "how do i make a farm"],
	["como encanto", "how do i enchant"],
	["mesa de encantamientos", "enchanting table"],
	["como hago pociones", "how do i brew potions"],
	["consejos de mineria", "mining tips"],
	["consejo de mineria", "mining tip"],
	["dame un consejo", "give me a tip"],
	["dato curioso", "fun fact"],
	["dime un dato", "tell me a fact"],
	["cuanto es", "what is"],
	["cuanto da", "what is"],
	// --- despedidas ---
	["me voy a dormir", "i am going to sleep"],
	["voy a dormir", "i am going to sleep"],
	["me voy", "i am leaving"],
	["ya vuelvo", "be right back"],
	["ya regreso", "be right back"],
	["donde queda", "where is"],
	["en donde hay", "where is there"],
	["donde puedo encontrar", "where can i find"],
	["donde se encuentra", "where is"],
	["ayudame a encontrar", "help me find"],
	["puedes buscar", "can you find"],
	["puedes encontrar", "can you find"],
	["puedes localizar", "can you locate"],
	["hay alguna", "is there a"],
	["hay algun", "is there a"],
	["existe alguna", "is there a"],
	["cual es la mas cercana", "which is the nearest"],
	["la mas cercana", "the nearest"],
	["mas cercana", "nearest"],
	["mas cercano", "nearest"],
	["el mas cercano", "the nearest"],
	["que hay cerca", "what is nearby"],
	["que hay por aqui", "what is around here"],
	["alguna estructura cerca", "any structure nearby"],
	["vete", "go away"],
	["alejate", "go away"],
	["dejame en paz", "leave me alone"],
	["dejame solo", "leave me alone"],
	["regresa", "come back"],
	["vuelve", "come back"],
	["baila", "dance"],
	["salta", "jump"],
	["que dijiste", "what did you say"],
	["repite eso", "say that again"],
	["repitelo", "say it again"],
	["no entiendo", "i dont understand"],
	["no entendi", "i didnt understand"],
	["que significa", "what does it mean"],
	["que es un", "what is a"],
	["que es una", "what is a"],
	["que es el", "what is the"],
	["que es la", "what is the"],
	["que son los", "what are the"],
	["que son las", "what are the"],
	["para que sirve", "what is it for"],
	["como se hace", "how do you make"],
	["como hago", "how do i make"],
	["como se craftea", "how do you craft"],
	["como crafteo", "how do i craft"],
	["como consigo", "how do i get"],
	["como obtengo", "how do i get"],
	["como encuentro", "how do i find"],
	["como funciona", "how does it work"],
	["como se llama", "what is the name of"],
	["cuantos dias", "how many days"],
	["cuanto tiempo", "how long"],
	["cuanto falta", "how long until"],
	["estas ocupada", "are you busy"],
	["estas ocupado", "are you busy"],
	["me puedes ayudar", "can you help me"],
	["me ayudas", "can you help me"],
	["estas despierta", "are you awake"],
	["estas despierto", "are you awake"],
	["sigues despierta", "are you awake"],
	["escanea", "scan for"],
	["escanear", "scan for"],
	["oye verity", "hey verity"],
	["hola verity", "hello verity"],
];

// Palabras sueltas (con límites de palabra). Sin acentos, en minúsculas.
const PALABRAS = {
	hola: "hello", adios: "bye", chao: "bye", gracias: "thanks",
	si: "yes", claro: "sure", vale: "okay", bueno: "okay",
	donde: "where", como: "how", cual: "which", cuales: "which",
	quien: "who", quienes: "who", cuando: "when",
	cuanto: "how much", cuantos: "how many", cuantas: "how many",
	busca: "find", buscar: "find", buscame: "find me", encuentra: "find",
	encontrar: "find", localiza: "locate", localizar: "locate",
	hallar: "find", hay: "is there", habra: "is there",
	quiero: "i want", quisiera: "i would like", necesito: "i need",
	puedes: "can you", podrias: "could you", puedo: "can i",
	ayuda: "help", ayudame: "help me", socorro: "help",
	dime: "tell me", cuentame: "tell me", dame: "give me",
	muestrame: "show me", ensename: "show me", llevame: "take me",
	guiame: "guide me", ven: "come", aqui: "here", aca: "here",
	alla: "there", ahi: "there", cerca: "near", cercano: "nearest",
	cercana: "nearest", lejos: "far", distancia: "distance",
	direccion: "direction", camino: "way", ir: "go", voy: "i go",
	vamos: "lets go", llegar: "reach", llego: "get to",
	// mundo
	aldea: "village", pueblo: "village", aldeas: "villages",
	aldeano: "villager", aldeanos: "villagers",
	bioma: "biome", biomas: "biomes", estructura: "structure",
	estructuras: "structures", coordenadas: "coordinates",
	coordenada: "coordinate", posicion: "position", ubicacion: "location",
	mapa: "map", brujula: "compass", spawn: "spawn",
	hora: "time", tiempo: "time", clima: "weather",
	lluvia: "rain", llueve: "rain", llover: "rain", tormenta: "storm",
	trueno: "thunder", noche: "night", dia: "day", manana: "morning",
	tarde: "afternoon", amanecer: "sunrise", atardecer: "sunset",
	dimension: "dimension", mundo: "world", jugadores: "players",
	jugador: "player", vida: "health", salud: "health", hambre: "hunger",
	seguro: "safe", peligro: "danger", peligroso: "dangerous",
	fortaleza: "stronghold", mansion: "mansion", monumento: "monument",
	templo: "temple", piramide: "pyramid", naufragio: "shipwreck",
	iglu: "igloo", bastion: "bastion", ruinas: "ruins", ruina: "ruin",
	tesoro: "treasure", portal: "portal",
	desierto: "desert", selva: "jungle", jungla: "jungle",
	bosque: "forest", llanura: "plains", pradera: "plains",
	montana: "mountain", montanas: "mountains", oceano: "ocean",
	mar: "ocean", pantano: "swamp", sabana: "savanna",
	nieve: "snow", nevado: "snowy", playa: "beach", rio: "river",
	cueva: "cave", cuevas: "caves", hielo: "ice", hongos: "mushroom",
	champinones: "mushroom", cerezo: "cherry", cerezos: "cherry",
	// minerales
	diamante: "diamond", diamantes: "diamonds", hierro: "iron",
	oro: "gold", carbon: "coal", cobre: "copper",
	esmeralda: "emerald", esmeraldas: "emeralds",
	lapislazuli: "lapis", lapiz: "lapis", redstone: "redstone",
	netherita: "netherite", netherite: "netherite",
	obsidiana: "obsidian", mineral: "ore", minerales: "ores",
	mena: "ore", minar: "mine", mino: "mine", mineria: "mining",
	capa: "layer", nivel: "level", profundo: "deep",
	excavar: "dig", cavar: "dig",
	// mobs
	vaca: "cow", vacas: "cows", cerdo: "pig", cerdos: "pigs",
	oveja: "sheep", ovejas: "sheep", pollo: "chicken",
	gallina: "chicken", lobo: "wolf", lobos: "wolves",
	gato: "cat", gatos: "cats", perro: "dog", perros: "dogs",
	arana: "spider", aranas: "spiders", esqueleto: "skeleton",
	esqueletos: "skeletons", zombi: "zombie", zombis: "zombies",
	creeper: "creeper", enderman: "enderman", bruja: "witch",
	abeja: "bee", abejas: "bees", golem: "golem", caballo: "horse",
	loro: "parrot", saqueador: "pillager", saqueadores: "pillagers",
	guardian: "guardian", dragon: "dragon", mob: "mob", mobs: "mobs",
	monstruo: "monster", monstruos: "monsters", animal: "animal",
	animales: "animals", mascota: "pet", domesticar: "tame",
	// objetos / acciones
	cama: "bed", antorcha: "torch", antorchas: "torches",
	comida: "food", comer: "eat", casa: "house", refugio: "shelter",
	base: "base", granja: "farm", pocion: "potion", pociones: "potions",
	encantamiento: "enchant", encantamientos: "enchants",
	encantar: "enchant", armadura: "armor", espada: "sword",
	pico: "pickaxe", hacha: "axe", pala: "shovel", arco: "bow",
	escudo: "shield", cubo: "bucket", agua: "water", lava: "lava",
	fuego: "fire", arbol: "tree", arboles: "trees", madera: "wood",
	piedra: "stone", tierra: "dirt", bloque: "block", bloques: "blocks",
	construir: "build", construye: "build", crear: "craft",
	craftear: "craft", explorar: "explore", explora: "explore",
	dormir: "sleep", duermo: "sleep", despierto: "awake", despierta: "awake", escanea: "scan",
	perdido: "lost", perdida: "lost", morir: "die", mori: "died",
	muerte: "death", atrapado: "stuck", hoyo: "hole", pozo: "hole",
	caer: "fall", cai: "fell", saltar: "jump", correr: "run",
	nadar: "swim", volar: "fly", pelear: "fight", matar: "kill",
	comerciar: "trade", intercambiar: "trade",
	// musica / sonidos
	musica: "music", cancion: "song", canciones: "songs",
	canta: "sing", cantar: "sing", toca: "play", reproduce: "play",
	pon: "play", sonido: "sound", sonidos: "sounds", ruido: "noise",
	escuchar: "listen", escucha: "listen", oye: "hey", para: "for",
	detente: "stop", alto: "high", sigue: "keep going",
	// social
	amigo: "friend", amiga: "friend", amigos: "friends",
	chiste: "joke", chistes: "jokes", historia: "story",
	triste: "sad", feliz: "happy", contento: "happy",
	aburrido: "bored", aburrida: "bored", miedo: "fear",
	asustado: "scared", asustada: "scared", enojado: "angry",
	enojada: "angry", cansado: "tired", cansada: "tired",
	estresado: "stressed", estresada: "stressed",
	emocionado: "excited", emocionada: "excited",
	orgulloso: "proud", orgullosa: "proud",
	tonto: "stupid", tonta: "stupid", estupido: "stupid",
	estupida: "stupid", idiota: "idiot", feo: "ugly", fea: "ugly",
	inutil: "useless", basura: "trash", odio: "hate",
	nombre: "name", edad: "age", creador: "creator", creo: "made",
	hizo: "made", verdad: "true", mentira: "lie", broma: "joke",
	// conectores (van al final; palabras cortas y comunes)
	el: "the", la: "the", los: "the", las: "the",
	un: "a", una: "a", unos: "some", unas: "some",
	de: "of", del: "of the", en: "in", con: "with", sin: "without",
	y: "and", o: "or", pero: "but", porque: "because",
	mi: "my", mis: "my", tu: "your", tus: "your",
	yo: "i", nosotros: "we", ellos: "they",
	es: "is", son: "are", esta: "is", estan: "are",
	estoy: "i am", soy: "i am", eres: "you are", estas: "you are",
	tengo: "i have", tienes: "you have", tiene: "has",
	fue: "was", era: "was", sera: "will be", hacer: "do",
	hace: "does", haz: "make", muy: "very", mucho: "a lot",
	mas: "more", menos: "less", poco: "little", nada: "nothing",
	algo: "something", alguien: "someone", nadie: "nobody",
	todo: "everything", todos: "all", otra: "another", otro: "another",
	ahora: "now", despues: "later", antes: "before", siempre: "always",
	nunca: "never", tambien: "too", solo: "alone", este: "this",
	esto: "this", esta_cosa: "this", eso: "that", ese: "that",
	esa: "that", aquel: "that", favor: "please", porfa: "please",
	norte: "north", sur: "south", oeste: "west",
	arriba: "up", abajo: "down", dentro: "inside", fuera: "outside",
	grande: "big", pequeno: "small", nuevo: "new", viejo: "old",
	mejor: "best", peor: "worst", rapido: "fast", lento: "slow",
	encuentrame: "find me", buscame: "find me", localizame: "locate",
	queda: "is", sirve: "works", significa: "means", funciona: "works",
	existe: "is there", existen: "are there", alguna: "any", algun: "any",
	colina: "hill", valle: "valley", isla: "island", laguna: "lake",
	lago: "lake", cascada: "waterfall", volcan: "volcano",
	profundidad: "depth", altura: "height", cielo: "sky", suelo: "ground",
	luna: "moon", sol: "sun", estrella: "star", estrellas: "stars",
	semilla: "seed", semillas: "seeds", trigo: "wheat", pan: "bread",
	carne: "meat", pescado: "fish", pescar: "fishing", manzana: "apple",
	papa: "potato", zanahoria: "carrot", huevo: "egg", leche: "milk",
	cofre: "chest", horno: "furnace", mesa: "table", crafteo: "crafting",
	yunque: "anvil", libreria: "bookshelf", libro: "book", libros: "books",
	mapa_del_tesoro: "treasure map", elytra: "elytra", alas: "elytra",
	tridente: "trident", ballesta: "crossbow", flecha: "arrow",
	flechas: "arrows", perla: "pearl", perlas: "pearls", ojo: "eye",
	ojos: "eyes", blaze: "blaze", ghast: "ghast", piglin: "piglin",
	wither: "wither", esquelet: "skeleton", slime: "slime",
	phantom: "phantom", vex: "vex", allay: "allay", camello: "camel",
	zorro: "fox", panda: "panda", ajolote: "axolotl", delfin: "dolphin",
	tortuga: "turtle", conejo: "rabbit", cabra: "goat", rana: "frog",
	murcielago: "bat", calamar: "squid", oso: "bear", polar: "polar",
	domestica: "tame", montar: "ride", monta: "ride", alimentar: "feed",
	alimenta: "feed", curar: "heal", cura: "heal", revivir: "revive",
	arregla: "fix", arreglar: "fix", repara: "repair", reparar: "repair",
	muestrame_esto: "show me", ensena: "show", indicame: "point me",
	guia: "guide", norte_de: "north of", cerca_de: "near",
};

// Matemáticas: "cuanto es 5 mas 3" → "what is 5 plus 3"
/** @param {string} t */
function traducirMatematicas(t) {
	let s = t;
	s = s.replace(/(\d)\s*mas\s*(\d)/g, "$1 plus $2");
	s = s.replace(/(\d)\s*menos\s*(\d)/g, "$1 minus $2");
	s = s.replace(/(\d)\s*por\s*(\d)/g, "$1 times $2");
	s = s.replace(/(\d)\s*(?:entre|dividido(?:\s+(?:por|entre))?)\s*(\d)/g, "$1 divided by $2");
	s = s.replace(/\braiz cuadrada de\b/g, "square root of");
	s = s.replace(/\bal cuadrado\b/g, "squared");
	s = s.replace(/\bal cubo\b/g, "cubed");
	s = s.replace(/\bpor ciento\b/g, "percent");
	return s;
}

let FRASES_ORDENADAS = null;
function frasesOrdenadas() {
	if (!FRASES_ORDENADAS) {
		FRASES_ORDENADAS = [...FRASES].sort((a, b) => b[0].length - a[0].length);
	}
	return FRASES_ORDENADAS;
}

/**
 * ¿Parece español? Solo traducimos si hay señales claras,
 * para no tocar los mensajes en inglés.
 * @param {string} texto
 */
export function pareceEspanol(texto) {
	if (/[áéíóúñ¿¡]/i.test(texto)) return true;
	const limpio = quitarAcentos(texto.toLowerCase());
	// Necesita al menos una pista fuerte que no exista en inglés.
	const fuertes =
		/\b(que|donde|como|cual(es)?|cuanto|cuantos|cuantas|quien(es)?|cuando|hola|buenas|buenos|gracias|adios|chao|busca(me|r)?|encuentra|encontrar|localiza(r)?|quiero|quisiera|puedes|podrias|puedo|necesito|ayuda(me)?|dime|dame|muestrame|ensename|llevame|guiame|sigueme|seguirme|sigas|deja|dejame|quedate|espera(me)?|ven|detente|callate|oye|aldea(s)?|pueblo|bioma(s)?|diamante(s)?|hierro|oro|carbon|esmeralda(s)?|coordenadas|cancion(es)?|musica|sonido(s)?|chiste(s)?|historia|estoy|eres|soy|tengo|tienes|aqui|aca|cerca|lejos|hay|por favor|porfa|noche(s)?|dia(s)?|manana|tarde|hora|clima|lluvia|llueve|toca|canta|reproduce|cuentame|perdido|perdida|atrapado|casa|refugio|comida|hambre|dormir|morir|mori|vamos|amigo(s)?|amiga(s)?|triste|feliz|aburrido|aburrida|miedo|asustado|enojado|cansado|tonto|tonta|estupido|estupida|idiota|inutil|te quiero|te amo|te odio|otra vez|de nuevo|mas fuerte|para|verdad|mentira|nada|algo|tambien|mucho|muy|esta(n|s)?|es|son|el|la|los|las|un(a|os|as)?|del|al|con|sin|pero|porque|entre|hacia|hasta|desde|donde esta)\b/;
	if (fuertes.test(limpio)) return true;
	for (const [es] of FRASES) {
		if (es.length >= 4 && limpio.includes(es)) return true;
	}
	return false;
}

/**
 * Traduce un mensaje en español a palabras clave en inglés.
 * Si el mensaje no parece español, lo devuelve tal cual.
 * @param {string} mensaje
 */
export function traducirEspanol(mensaje) {
	if (typeof mensaje !== "string" || !mensaje.trim()) return mensaje;
	if (!pareceEspanol(mensaje)) return mensaje;

	let t = quitarAcentos(mensaje.toLowerCase());
	t = t.replace(/[¿¡]/g, " ");
	t = traducirMatematicas(t);

	for (const [es, en] of frasesOrdenadas()) {
		if (t.includes(es)) {
			t = t.split(es).join(en);
		}
	}

	t = t.replace(/\b([a-z]+)\b/g, (palabra) => PALABRAS[palabra] ?? palabra);
	t = t.replace(/\s{2,}/g, " ").trim();
	return t;
}
